name: Auto Delete Feature Branches

on:
  pull_request:
    types: [closed]

jobs:
  delete_feature_branch:
    runs-on: ubuntu-latest

    # Only run if the PR is merged, the head branch starts with 'feature/',
    # and the base branch is 'development'
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'feature/') &&
      (github.event.pull_request.base.ref == 'development')

    steps:
      - name: Delete branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          
          # Variables for convenience
          BRANCH=${{ github.event.pull_request.head.ref }}
          REPO=${{ github.repository }}
          
          # Clone the repo so we can push the deletion
          git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${REPO}.git"
          cd "$(basename "$REPO")"
          
          # Delete the remote branch
          git push origin --delete "${BRANCH}"
