name: Auto-delete feature branches

# Trigger on pull request closed event
on:
  pull_request:
    types: [closed]
  schedule:
    - cron: "0 2 * * *"

jobs:
  delete-merged-branch:
    # Run only when the PR is actually merged,
    # the base branch is `development`, and the head starts with `feature/`
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'feature/') &&
      (github.event.pull_request.base.ref == 'development')
    runs-on: ubuntu-latest

    steps:
      - name: Delete merged head branch
        uses: actions/github-script@v6
        with:
          script: |
            const ref = context.payload.pull_request.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // We delete the reference "heads/branchName"
            await github.git.deleteRef({
              owner,
              repo,
              ref: `heads/${ref}`
            });

